## --------------------------------------for production
#spring.application.name=journalApp
#spring.data.mongodb.uri=mongodb+srv://admin:test123@cluster0.o9zck.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journaldb
#spring.data.mongodb.auto-index-creation=true
#
#
## --------------------------------------for development
##spring.data.mongodb.host=localhost
##spring.data.mongodb.port=27017
